// Extended detail for each service. SERVICE_DETAILS is keyed by slug
// and provides intro copy, deliverables, process, tools, FAQ, stats.

const SERVICE_DETAILS = {
  'web-development': {
    eyebrow: '§ 01 — Web Development',
    intro: 'Production-grade websites built for shipping speed and conversion. Whether that\'s a marketing site you can update in Notion, a landing-page system your team can publish without engineering, or the app shell behind your product — I build sites that load fast, convert well, and don\'t rot.',
    headline: ['Marketing sites,', 'landing pages,', 'and app shells.'],
    timeline: { length: '6 — 8 weeks', shape: 'Project · fixed-fee', note: 'Per build. Multi-site programmes scoped separately.' },
    deliverables: [
      'Production-deployed Next.js or Astro codebase',
      'Headless CMS configured (Sanity / Contentful / Notion)',
      'Component library + Storybook for your team',
      'Edge-deployed via Vercel or Cloudflare',
      'Lighthouse 95+ on all four metrics',
      'Analytics, tracking & A/B framework wired in',
      'Written runbook + 60-day support window',
    ],
    process: [
      { n: '01', name: 'Discovery', body: 'Two-week sprint mapping the site\'s job — audiences, journeys, content model, conversion goals. You leave the discovery with wireframes and a content matrix.' },
      { n: '02', name: 'Design system', body: 'Tokens, components, and 3–5 key page templates designed in code, not Figma-first. Iterating in the browser is faster than in mockups.' },
      { n: '03', name: 'Build', body: 'Daily commits in a real branch you can preview. Bi-weekly demos, scoped tickets, no surprise scope.' },
      { n: '04', name: 'Ship & handover', body: 'Performance audit, security review, CMS-author training, and a written runbook. Then I disappear and your team owns it.' },
    ],
    tools: ['Next.js', 'Astro', 'TypeScript', 'Tailwind', 'Sanity', 'Contentful', 'Vercel', 'Cloudflare', 'Storybook'],
    stat: { k: '95+', label: 'Lighthouse · all metrics, every project' },
    faq: [
      { q: 'Will my team be able to update the site?', a: 'Yes. The CMS is the source of truth — copy, images, even page sections are editable without engineering. I train your team on it during handover.' },
      { q: 'Do you work with existing codebases?', a: 'Often. If the bones are solid (modern framework, sane architecture) I extend them. If they\'re not, we have a frank conversation about a rebuild.' },
      { q: 'What about ecommerce?', a: 'Yes — Shopify Hydrogen, Medusa, or custom Stripe Checkout. Get in touch with the product complexity and we\'ll pick the right tool.' },
    ],
  },
  'ppc': {
    eyebrow: '§ 02 — PPC & Paid Acquisition',
    intro: 'A twelve-month paid-acquisition programme run like an engineering team. Google, Meta, LinkedIn, TikTok — instrumented end-to-end on offline conversions, not vanity metrics. The goal isn\'t to spend more; it\'s to know exactly what every dollar is doing.',
    headline: ['A year-long', 'paid programme,', 'engineered.'],
    timeline: { length: '12 months', shape: 'Programme · monthly + performance', note: 'Minimum commitment. Reviewed quarterly.' },
    deliverables: [
      'Full account audit + restructure across all platforms',
      'Server-side conversion APIs on every channel (Google, Meta, LinkedIn, TikTok)',
      'Creative testing system shipping 20+ ads / week',
      'Weekly performance reviews + monthly written reports',
      'Quarterly incrementality tests (geo-holdouts)',
      'MMM-lite attribution model in your warehouse',
      'Annual budget plan + media-mix recommendation',
    ],
    process: [
      { n: '01', name: 'Audit (Month 1)', body: 'Account-level teardown across every channel. Find the waste, the wins, and the gaps. Restructure the account hierarchy for scale.' },
      { n: '02', name: 'Instrument (Month 1—2)', body: 'Server-side conversions on every channel. Identity resolution. The plumbing that recovers 30–40% of signal lost to iOS / cookie depreciation.' },
      { n: '03', name: 'Scale (Month 2—12)', body: 'Weekly creative shipping, ongoing budget reallocation, and constant testing. Two-week rolling sprints with clear hypotheses.' },
      { n: '04', name: 'Compound', body: 'Quarterly incrementality reviews. Annual planning. The programme gets smarter every month — that\'s the point of doing it for a year.' },
    ],
    tools: ['Google Ads', 'Meta Ads', 'LinkedIn Ads', 'TikTok Ads', 'Apple SA', 'GTM Server', 'Segment', 'BigQuery', 'Looker'],
    stat: { k: '−42%', label: 'Avg. cost-per-qualified-lead · year 1' },
    faq: [
      { q: 'What\'s the minimum monthly spend?', a: 'I\'m most useful from $30k/mo upward — below that, the operator overhead doesn\'t make sense. If you\'re smaller, I can point you to better-suited specialists.' },
      { q: 'Do you work with our existing agency?', a: 'Sometimes. Often the cleanest version is replacing them. But if you have a creative shop or platform-specialist you love, I orchestrate around them.' },
      { q: 'What happens after twelve months?', a: 'Most clients renew. A few graduate to running it in-house with my fractional support. The handover docs make either path workable.' },
    ],
  },
  'tracking': {
    eyebrow: '§ 03 — Data Tracking & Implementation',
    intro: 'The plumbing nobody wants to think about — until it\'s broken. Tracking is the foundation every later decision rests on, and most companies\' tracking is held together with duct tape. I rebuild it once, properly, on first-party infrastructure you own.',
    headline: ['First-party', 'tracking, done', 'once, properly.'],
    timeline: { length: '4 — 8 weeks', shape: 'Project · fixed-fee', note: 'Per implementation. Often paired with PPC or Engine Build.' },
    deliverables: [
      'Server-side GTM container on your own subdomain',
      'Event taxonomy + naming conventions (documented)',
      'Amplitude / Mixpanel / GA4 instrumented end-to-end',
      'Identity resolution: anon → known user, cross-device',
      'Warehouse pipeline into BigQuery / Snowflake / DuckDB',
      'Privacy/consent banner wired correctly (not as theatre)',
      'Tracking spec document for your engineering team',
    ],
    process: [
      { n: '01', name: 'Audit', body: 'Map every event, every tool, every dashboard. Find the duplicates, the misses, the broken stuff. You leave with a written assessment.' },
      { n: '02', name: 'Spec', body: 'Design a clean event taxonomy. Naming conventions. Who fires what, when, with which properties. This is the document your team will reference for years.' },
      { n: '03', name: 'Implement', body: 'Server-side first. Client-side as backup. Test events fire correctly across browsers, ad-blockers, and platforms. Validate against the spec.' },
      { n: '04', name: 'Train', body: 'Your analytics team learns the taxonomy. Your engineers learn to add events without breaking it. Dashboards rebuilt against the new foundation.' },
    ],
    tools: ['GTM Server', 'Amplitude', 'Mixpanel', 'GA4', 'Segment', 'RudderStack', 'BigQuery', 'Snowflake', 'DuckDB'],
    stat: { k: '+38%', label: 'Conversion signal recovered · iOS / CMP-affected' },
    faq: [
      { q: 'Do we need a warehouse?', a: 'Eventually, yes. Even if you\'re not using one today, I\'ll set up the pipeline so it lands somewhere queryable. BigQuery is free for the first terabyte — there\'s no reason not to.' },
      { q: 'What about privacy / GDPR?', a: 'The CMP layer is part of the implementation, not an afterthought. Consent-mode handled correctly so you stay compliant without losing the signal.' },
      { q: 'Can you fix tracking without ripping it out?', a: 'Sometimes — but in 80% of audits, the existing setup has accumulated enough drift that a clean rebuild is faster than patching. I\'ll tell you honestly.' },
    ],
  },
  'business-software': {
    eyebrow: '§ 04 — Business Software',
    intro: 'The operational software a growing company needs but never has time to build — invoicing portals, ops dashboards, CRMs, billing systems. I build the back-office tools that compound your team\'s leverage. Usually on Retool or with bespoke code, depending on what fits.',
    headline: ['Internal tools', 'your team', 'actually uses.'],
    timeline: { length: '2 — 6 months', shape: 'Project · fixed-fee per tool', note: 'Per tool. Multiple parallel tools negotiable.' },
    deliverables: [
      'Bespoke internal app (Retool / Internal / custom React)',
      'Authentication, role-based permissions, audit log',
      'Stripe / billing integration (subscriptions, metering, invoicing)',
      'Workflow automation (n8n, Zapier, or custom backends)',
      'Slack/Linear/Email alerting & approvals',
      'Live data dashboards from your warehouse',
      'Written runbook + ongoing maintenance handoff',
    ],
    process: [
      { n: '01', name: 'Workflow audit', body: 'Shadow your team for a week. Find the manual steps, the spreadsheets passed by email, the Slack messages that should be tickets. Prioritise by hours-saved.' },
      { n: '02', name: 'Prototype', body: 'Sketch the tool in Retool by week two. Real data, real workflows. Your team uses it before it\'s "done" — feedback is fast.' },
      { n: '03', name: 'Productionise', body: 'Auth, audit logs, error handling, the unsexy stuff. Either stay in Retool or graduate to bespoke code if the tool justifies it.' },
      { n: '04', name: 'Handover', body: 'Your team — or a friendly engineer — owns it. I document everything. Optional ongoing maintenance arrangement.' },
    ],
    tools: ['Retool', 'Internal', 'React', 'Node', 'Stripe', 'n8n', 'Zapier', 'Slack API', 'Linear API'],
    stat: { k: '12 hrs/wk', label: 'Avg. team-hours reclaimed per tool' },
    faq: [
      { q: 'Retool vs. bespoke — which?', a: 'Default to Retool. Move to bespoke when the tool is customer-facing, performance-critical, or going to outlive Retool\'s pricing curve.' },
      { q: 'Will we be locked into Retool?', a: 'No more than you\'re locked into any SaaS. Most Retool apps can be rewritten in a week of React work if you need to leave.' },
      { q: 'Can you replace our CRM?', a: 'I\'d rather not. CRMs are calcified for good reason. I build the tools that surround your CRM — better workflows on top, better dashboards underneath.' },
    ],
  },
  'optimization': {
    eyebrow: '§ 05 — Optimization & Conversion',
    intro: 'Conversion rate optimisation done as a programme, not a one-off audit. Eight to twelve weeks of focused experimentation against the highest-leverage flows in your funnel — onboarding, checkout, pricing — with win rates measured and results documented.',
    headline: ['Higher conversion,', 'measured properly,', 'shipped weekly.'],
    timeline: { length: '8 — 12 weeks', shape: 'Sprint · fixed-fee', note: 'Per programme. Renewable for new flows.' },
    deliverables: [
      'Full funnel teardown with prioritised hypothesis list',
      'A/B testing infrastructure (LaunchDarkly / Optimizely / GrowthBook)',
      '6–12 shipped experiments with statistical rigor',
      'Redesigned high-impact pages (onboarding, pricing, checkout)',
      'Onboarding instrumentation (tours, checklists, prompts)',
      'Win rate report + documented learnings',
      'Playbook for your team to run experiments after I leave',
    ],
    process: [
      { n: '01', name: 'Teardown', body: 'Heuristic + data-driven audit of the funnel. Where are users dropping, why, what does the analytics actually say. Hypothesis ranked by expected impact.' },
      { n: '02', name: 'Set up', body: 'Experimentation platform configured. Stats engine validated. Tracking events in place. The team learns the protocol.' },
      { n: '03', name: 'Ship', body: 'Two-week cycles. One winning test per cycle is the target. Win, lose, or learn — every test gets a writeup.' },
      { n: '04', name: 'Compound', body: 'The biggest gains come from the winners getting shipped to production and the losing variants killed quickly. We measure the cumulative lift, not individual tests.' },
    ],
    tools: ['LaunchDarkly', 'Optimizely', 'GrowthBook', 'PostHog', 'Statsig', 'VWO', 'FullStory', 'Hotjar'],
    stat: { k: '+38%', label: 'Avg. trial-to-paid uplift · 12-week sprints' },
    faq: [
      { q: 'How much traffic do we need?', a: 'For binary conversion tests, you want ~1,000 conversions/week minimum. For lower-volume pages we use Bayesian methods + qualitative research instead.' },
      { q: 'What if our tests don\'t win?', a: 'Half of mine don\'t. That\'s why we ship in cycles. The winners pay for the losers, and the losers teach you about your users. Bad sign is when nothing moves — that means you need bigger swings.' },
      { q: 'Do you do redesigns?', a: 'Yes — pages with clear conversion goals get redesigned, not just A/B-tested. Full-page rewrites against fresh hypotheses, then validated.' },
    ],
  },
  'analytics': {
    eyebrow: '§ 06 — Data & Analytics',
    intro: 'Once tracking exists, someone has to read it. Quarterly engagements where I dig into your funnel, retention, attribution and technical SEO and tell you what changed, why, and what to ship next. Less dashboards, more decisions.',
    headline: ['Less dashboards,', 'more decisions.'],
    timeline: { length: 'Quarterly', shape: 'Engagement · 4 weeks per quarter', note: 'Ongoing. Cancel any quarter, no fault.' },
    deliverables: [
      'Funnel & drop-off analysis (mapped to user journey)',
      'Retention cohort report (D1/D7/D30, segment-level)',
      'Attribution & channel-mix analysis (last-touch + MMM-lite)',
      'Technical SEO audit (page speed, schema, sitemaps, indexation)',
      'Quarterly insight memo (5–10 pages, written, decisions-oriented)',
      'Working session with leadership to prioritise next quarter',
      'Annual retrospective + planning support',
    ],
    process: [
      { n: '01', name: 'Pull', body: 'Connect to your warehouse. Pull the quarter\'s data. Run the standard battery — funnels, retention, attribution, SEO.' },
      { n: '02', name: 'Interrogate', body: 'Don\'t just report — interrogate. Why did retention dip in cohort X? What does the SEO traffic correlate with? Where\'s the lift hiding?' },
      { n: '03', name: 'Write', body: 'A short, opinionated memo. What I\'d do next, ranked. No dashboards. No 60-slide decks. A 5-page document that points at decisions.' },
      { n: '04', name: 'Workshop', body: 'A 90-minute working session with your leadership team. Pick the next quarter\'s priorities. Then I disappear for 12 weeks.' },
    ],
    tools: ['Amplitude', 'Mixpanel', 'GA4', 'Looker', 'Mode', 'Hex', 'dbt', 'Ahrefs', 'Screaming Frog'],
    stat: { k: '5 pages', label: 'Quarterly memo. No 60-slide decks.' },
    faq: [
      { q: 'Do we get a dashboard?', a: 'You get a memo. Dashboards are great for monitoring, terrible for decisions. If you need dashboards, the Tracking service builds those — Analytics is for the strategic layer above them.' },
      { q: 'Can you train our analyst?', a: 'Yes — I often pair with internal analyst hires. The quarterly cycle becomes a coaching loop as they learn to do it without me.' },
      { q: 'What about real-time?', a: 'You probably don\'t need real-time. Quarterly is right for strategy. Weekly is right for ops. Hourly is right for fraud detection. Pick the cadence to the question.' },
    ],
  },
  'automation': {
    eyebrow: '§ 07 — Marketing Automation',
    intro: 'The systems that make your product feel attentive — behaviour-triggered messages, personalisation, viral loops. Built well, automation is the leverage that lets a small team feel like a big one. Built badly, it\'s the unread email graveyard.',
    headline: ['Lifecycle systems', 'that compound,', 'not interrupt.'],
    timeline: { length: '3 — 6 months', shape: 'Programme · fixed-fee', note: 'Per lifecycle programme. Long-term operatorship optional.' },
    deliverables: [
      'Behavior-triggered messaging (email, SMS, push) on real events',
      'Personalisation engine for the web (geo, industry, referrer)',
      'Viral & referral system with reward dashboard',
      'Lifecycle email designed (onboarding, activation, win-back)',
      'Templates + tone-of-voice documentation for your team',
      'Performance dashboards per campaign',
      'Quarterly programme review',
    ],
    process: [
      { n: '01', name: 'Map', body: 'Customer journey, end-to-end. Where are the moments of attention? Onboarding, drop-off, expansion, churn. Each moment gets a sequence.' },
      { n: '02', name: 'Write', body: 'The hardest part. Sequences are only useful if the copy is good. We write them together — your voice, my structure.' },
      { n: '03', name: 'Wire', body: 'Set up in Customer.io / Braze / Iterable. Triggers on real events from your tracking layer. Tested against staging users first.' },
      { n: '04', name: 'Iterate', body: 'Monthly performance reviews. Kill what doesn\'t work, double down on what does. Goal isn\'t opens — it\'s product behaviour.' },
    ],
    tools: ['Customer.io', 'Braze', 'Iterable', 'Loops', 'Resend', 'Twilio', 'OneSignal', 'Mutable', 'Hightouch'],
    stat: { k: '3.1×', label: 'Avg. lift in trial-to-paid · onboarding sequences' },
    faq: [
      { q: 'Will users hate the volume?', a: 'They won\'t if you write less. My default is to start with half the messages people expect — only add when there\'s a clear job to do. Email frequency is a UX problem, not a marketing one.' },
      { q: 'Do you write the copy?', a: 'I draft, you edit, we iterate. Voice is yours; structure and triggers are mine.' },
      { q: 'Can you build referral loops?', a: 'Yes — invite mechanics, reward dashboards, tracking links, the whole flow. Often paired with the Engine Build for tight integration into product.' },
    ],
  },
};

Object.assign(window, { SERVICE_DETAILS });
